### PR TITLE
README.md: Add Travis build status badge, formatting

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR fixes the small display issue that there were _ being rendered between icons that were linked.

Also adds a Travis build status badge.

### CODE REVIEW

**Comment by mekya** [comment]
Thank you so much @olleolleolle for your contribution. 

We can send you a starbucks gift card or something similar to show our appreciation to your contribution.

**Comment by olleolleolle** [comment]
@mekya If you can celebrate by donating to Doctors Without Borders, that'd make me happy.  ☕ Cool project!

**Comment by olleolleolle** [comment]
@mekya Absolutely, that's the one.

**Comment by mekya** [comment]
Hi @olleolleolle,
I've donated to Doctors Without Borders.

TBH, we would send about $5 for your coffee gift card. Fortunately, we've donated much more to the Doctors Without Borders on your behalf. Thank you for this opportunity. I would send the receipt to you if you want to see.

Cheers
Oguz

**Comment by olleolleolle** [comment]
No need for a receipt between friends. Thank you!

**Comment by Mohit-3196** [comment]
Thank you again @olleolleolle,
The PR has been merged.

**Pull request merged**
