### PR TITLE
Support S3 Permissions while uploading the files

### PR DESCRIPTION
**Pull request by mekya**
https://github.com/ant-media/Ant-Media-Server/issues/3677

### CODE REVIEW

**Comment by peterzanetti** [comment]
I am testing the snapshot that includes this change and S3 upload is now broken for me.

**Comment by mekya** [comment]
Hi @peterzanetti 

Thank you for letting us know. 

Have you installed the server in cluster over a previous one? Alternatively, you have a fresh installation?

**Comment by peterzanetti** [comment]
I've both installing fresh and over previous 2.4.1 snapshot, and S3 upload is non functioning in this latest snapshot.

**Comment by mekya** [comment]
Thank you @peterzanetti , I'll personally test it soon.

**Comment by mekya** [comment]
Hi @peterzanetti ,

I've just tested the latest branch and S3 is working for me. 

Which version have you exactly tried?

Regards,

**Comment by peterzanetti** [comment]
I am trying ant-media-server-enterprise-2.4.1-SNAPSHOT-20211108_0414

**Comment by peterzanetti** [comment]
@mekya I was provided a newer snapshot to test as well and it has the same issue. I've tried a few times going back and forth between the snapshot from 10/8 and the recent snapshots from November, and S3 upload does not work in the latest snapshots, but works fine in earlier. It does not seem to be configuration or environment issue, as it works fine in recent versions/snapshots.

**Comment by golgetahir** [comment]
Hi @peterzanetti 

Can you post some logs in between the moment you clicked on stop publish button and 15-20 second afterwards for the time s3 upload supposed to work.

**Comment by mekya** [comment]
It's weird. There are some changes about S3 so it may cause this break for you in your environment. is it possible to schedule a meeting and understand the problem  @peterzanetti @golgetahir?

**Comment by peterzanetti** [comment]
Yes we can, as soon as possible. Please reach out via email.

**Comment by mekya** [comment]
What is the latest status? As far as I know meetings have been scheduled.

**Pull request merged**
