### PR TITLE
Pass metadata from processPublishCommand to isPublishAllowed

### PR DESCRIPTION
**Pull request by lastpeony**
processPublishCommand function on enterprise takes metaData but it doesnt pass it to isPublishAllowed.

In previous PR metadata was retrieved through broadcast object to pass it webhook. In some cases(especially web conf) broadcast object is not created(null) thus eventhough client sends metadata it was not retrieved.

### CODE REVIEW

**Comment by mekya** [comment]
Hi @lastpeony ,
PR is failing. Please make it pass the CI and SonarCloud

**Comment by lastpeony** [comment]
> Hi @lastpeony , PR is failing. Please make it pass the CI and SonarCloud

SonarCloud is reporting a low coverage error for a file that may not be related to the code changes. Can you please review and confirm if the file in question is indeed not related?

**Comment by mekya** [comment]
This is a refactor for this issue  https://github.com/ant-media/Ant-Media-Server/issues/4829

**Review by mekya — APPROVED** [review]
Thank you for your work @lastpeony.

Just a reminder, changing interfaces has consequences so it should be changed everywhere.  Providing backward compatibility is important. If you had provided it, there would be fewer changes in the codebase.  

If we expose these APIs to the app developers, providing backward compatibility will be much more important than ever.  

Thank you

**Pull request merged**
