### PR TITLE
Add meta data information in callback

### PR DESCRIPTION
**Pull request by USAMAWIZARD**
https://github.com/ant-media/Ant-Media-Server/issues/5611

### CODE REVIEW

**Comment by mustafaboleken** [comment]
@USAMAWIZARD Can you please update insecure dependencies?

**Comment by USAMAWIZARD** [comment]
@mustafaboleken I have updated it

**Comment by mustafaboleken** [comment]
> @mustafaboleken I have updated it

Thank you, I tested the development and it's working fine. I'm waiting for the enterprise side also pass. Then, we can merge it.

**Review by mustafaboleken — APPROVED** [review]
lgtm

**Comment by mekya** [comment]
Closing the PR because this development is not required

**Pull request closed without merging**
