### PR TITLE
Fix Mongodb URI issue

### PR DESCRIPTION
**Pull request by USAMAWIZARD**
https://github.com/ant-media/Ant-Media-Server/issues/5344

### CODE REVIEW

**Comment by mekya** [comment]
Hi @USAMAWIZARD,

Thank you very much for the fix. I'm gently reminding you the test code. 

If we have the test code, we'll make sure that we don't have the same problem again in the same way and it serves the following principle in the manifesto 

>Solve problems permanently. Don’t waste time addressing the same issue multiple times.

**Comment by USAMAWIZARD** [comment]
Thanks @mekya abi I will try to implement the test cases.

**Comment by USAMAWIZARD** [comment]
Test Cases have been Added

**Review by mekya — APPROVED** [review]
Congrats @USAMAWIZARD 👏 

In this way, we'll make sure that we won't encounter the same problem again. So we spend our time on things that has an impact/results ;)

**Comment by USAMAWIZARD** [comment]
Thank you.

**Pull request merged**
