### PR TITLE
Support publishing and playing to the AMS behind on-prem NAT 

### PR DESCRIPTION
**Pull request by golgetahir**
https://github.com/ant-media/Ant-Media-Server/issues/3892

### CODE REVIEW

**Review by mekya — APPROVED** [review]

**Comment by rsnk96** [comment]
Hi @mekya @golgetahir 

Is there any guide on how this functionality can be achieved?

**Comment by mekya** [comment]
hi @rsnk96 ,

For a quick introduction, please check this out - 
"Play local IP cameras from anywhere"
https://antmedia.io/cool-things-srt-deploy-app-play-local-ip-cameras/

More detailed blog post is being prepared and it will be on the [antmedia.io](https://antmedia.io)

**Comment by rsnk96** [comment]
Thanks @mekya 

I think a post on Method #2 might also be of interest
_(In order to make the users watch the IP camera, Ant Media Server, running in the local network, should push the IP camera streams to the Ant Media Server running in the cloud. There is no security vulnerability but it consumes too much bandwidth all the time as both servers are streaming.)_

**Comment by mekya** [comment]
My pleasure @rsnk96 

It is also an another solution

**Pull request merged**
