### PR TITLE
edit cluster installation guide

### PR DESCRIPTION
**Pull request by timantmedia**
Improvements on the cluster installation guide.

### CODE REVIEW

**Comment by timantmedia** [comment]
@asharamseervi @mustafaboleken some more changes. Making this a draft because I want a way to allow others to preview these changes before I submit this PR for review. Is there any way this can be done?

**Comment by timantmedia** [comment]
@asharamseervi can this be merged into the documentation repository?

**Comment by asharamseervi** [comment]
Yes, sure. Tomorrow I'll merge these and close this pr!

**Comment by mustafaboleken** [comment]
I'm closing this right now. Let's move this changes to https://github.com/ant-media/ant-media-documentation

**Pull request closed without merging**
