### PR TITLE
SonarQube - Extracting constants from duplicated Strings with length >= 5

### PR DESCRIPTION
**Pull request by dvmarcilio**
Extracting constants from Strings that were duplicated at least 3 times. Considering only Strings with length >= 5.

This fixes several SonarQube issues for the rule: [String literals should not be duplicated](https://rules.sonarsource.com/java/RSPEC-1192)

### CODE REVIEW

**Comment by dvmarcilio** [comment]
Sounds good! I may not be able to write the tests in the next few days, but I'm up to it.

**Comment by mekya** [comment]
> Sounds good! I may not be able to write the tests in the next few days, but I'm up to it.

Then ignore classes for com.antstreaming. They will be removed.

**Comment by mekya** [comment]
I've removed com.antstreaming. packages @dvmarcilio

**Comment by mekya** [comment]
Source code has changed too much since this PR. Sorry for not merging timely. 
Closing this PR

**Pull request closed without merging**
