### PR TITLE
Add custom text support in stream endpoints for VoD & HLS

### PR DESCRIPTION
**Pull request by lastpeony**
https://github.com/ant-media/Ant-Media-Server/issues/6650

### CODE REVIEW

**Review by mekya — CHANGES_REQUESTED** [review]
Hi @lastpeony ,

I need the explanation in AppSettings fileNameFormat in javadoc format. 

The implementation seems to be complex for me.  Please take a look at what you can do to make it simple. 

Cheers

**Comment by lastpeony** [comment]
> Hi @lastpeony ,
> 
> I need the explanation in AppSettings fileNameFormat in javadoc format.
> 
> The implementation seems to be complex for me. Please take a look at what you can do to make it simple.
> 
> Cheers

Hello,
You are right. I sent a much simpler version. Please review again
Thanks

**Comment by lastpeony** [comment]
I also updated the javadoc.

**Comment by mekya** [comment]
Thank you @lastpeony for making it simple 👏

**Pull request merged**
