### PR TITLE
Make rtsp timeout configurable

### LINKED ISSUE #3582: No start RTSP playing
### Short description
Some times when you reboot the  rtsp  source, not start playing video but soud works fine, its appear some player like the 

 photo.
start

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version: Versión 92.0.4515.159 (Build oficial) (64 bits)

### Steps to reproduce

Some times when you reboot the camera   the rstp not started.

I can see that this  bug, may appear when you switch from tcp to udp protocol with out reboot the camera

 

### Logs
undefined4787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:14:46,116 [network_thread - 5229] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount
2021-08-30 11:14:46,117 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:14:51,117 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:14:51,309 [Thread-421] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor queue size: 0 for stream: 265664787423447357450588
2021-08-30 11:14:56,115 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:01,117 [network_thread - 5229] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount
2021-08-30 11:15:01,117 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:06,118 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:11,115 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:12,643 [Thread-421] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor queue size: 0 for stream: 265664787423447357450588
2021-08-30 11:15:16,113 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:16,126 [network_thread - 5229] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount
2021-08-30 11:15:21,118 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:26,115 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:31,114 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:31,124 [network_thread - 5229] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount
2021-08-30 11:15:33,975 [Thread-421] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor queue size: 0 for stream: 265664787423447357450588
2021-08-30 11:15:36,118 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:41,115 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:46,114 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:46,128 [network_thread - 5229] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount
2021-08-30 11:15:51,117 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:15:55,307 [Thread-421] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor queue size: 0 for stream: 265664787423447357450588
2021-08-30 11:15:56,114 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:01,114 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:01,115 [network_thread - 5229] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount
2021-08-30 11:16:06,118 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:11,115 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:16,115 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:16,126 [network_thread - 5229] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount
2021-08-30 11:16:16,641 [Thread-421] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor queue size: 0 for stream: 265664787423447357450588
2021-08-30 11:16:21,115 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:26,114 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:31,116 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:31,126 [network_thread - 5229] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount
2021-08-30 11:16:36,116 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:37,976 [Thread-421] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor queue size: 0 for stream: 265664787423447357450588
2021-08-30 11:16:41,115 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:46,116 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:46,121 [network_thread - 5229] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount
2021-08-30 11:16:51,115 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:56,113 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:16:59,308 [Thread-421] INFO  i.a.e.adaptive.StreamAdaptor - Stream adaptor queue size: 0 for stream: 265664787423447357450588
2021-08-30 11:17:01,116 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:17:01,128 [network_thread - 5229] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount
2021-08-30 11:17:06,115 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:17:11,115 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:17:13,455 [pool-5-thread-1] INFO  org.red5.server.tomcat.WarDeployer - Deploy wars with app start
2021-08-30 11:17:16,113 [vert.x-eventloop-thread-2] INFO  i.a.enterprise.webrtc.WebRTCAdaptor - Client:1329057650 for stream 265664787423447357450588 current video bitrate: 0 audio bitrate: 96000 webrtc client target bitrate: 10000000
2021-08-30 11:17:16,126 [network_thread - 5229] INFO  org.webrtc.Logging - Tag:WebRtcAudioTrackExternal - Message:GetPlayoutUnderrunCount

### PR DESCRIPTION
**Pull request by golgetahir**
https://github.com/ant-media/Ant-Media-Server/issues/3582

### CODE REVIEW

**Review by mekya — APPROVED** [review]

**Comment by Sclabb** [comment]
Hi, where is the file path to configure the rtsp timeout for a application  and what is the command like?

could you give me an example?

Thank you

**Comment by mekya** [comment]
Could you please [check this out](https://resources.antmedia.io/docs/ams-application-configuration?highlight=application%20properties)? 

Please let me know if you need help

**Comment by mekya** [comment]
Could you please [check this out](https://resources.antmedia.io/docs/ams-application-configuration?highlight=application%20properties)? 

Please let me know if you need help

**Comment by Sclabb** [comment]
What I have put in this way is it correct?
because it still does not work for me the start of the streaming is not delayed.
PHOTO

**Comment by mekya** [comment]
Hey @Sclabb ,

It seems that it's correct. On the other hand, your expectation and feature may not match. 

This feature does not delay the stream. This is the max duration that the server waits if it cannot receive stream while connecting to the RTSP resource.

**Comment by mekya** [comment]
Hey @Sclabb ,

It seems that it's correct. On the other hand, your expectation and feature may not match. 

This feature does not delay the stream. This is the max duration that the server waits if it cannot receive stream while connecting to the RTSP resource.

**Pull request merged**
