### PR TITLE
Webhook Authentication For WebRTC Play

### PR DESCRIPTION
**Pull request by lastpeony**
https://github.com/ant-media/Ant-Media-Server/issues/6211

With this form this PR breaks backward compatability of webhook publish authentication because there is a new app setting webhookPublishAuthEnabled and webhookPlayAuthEnabled
previously webhook auth was only for publish and webhook publish was enabled if webhook auth url is not empty.

### CODE REVIEW

**Comment by mekya** [comment]
hi @lastpeony ,

Thank you for the implementation. 

I read your comment and had a review of the PR. I'd like to discuss if there is an alternative way to make this implementation without breaking backward compatibility. Because the cost of breaking backward compatibility includes extra support and unhappy users, which may mean churn.

 Then my question is: What's the alternative implementation to not break backward compatibility?

**Review by mekya — CHANGES_REQUESTED** [review]
Commented on the PR directly to find out the way without breaking backward compatibility

**Comment by lastpeony** [comment]
Hi @mekya Thank you for the review.
We can eliminate webhookPublishAuthEnabled and webhookPlayAuthEnabled, and instead utilize webhookAuthUrl exclusively for publishing purposes while introducing a new setting for webhookPlayAuthUrl. This adjustment might appear confusing in the app settings, but with your approval, I can implement it to maintain backward compatibility.

**Review by mekya — APPROVED** [review]

**Comment by mekya** [comment]
Thank you @lastpeony

**Pull request merged**
