### PR TITLE
Fix HLS Modifier Returning Wrong Content in Case of Https

### PR DESCRIPTION
**Pull request by lastpeony**
https://github.com/ant-media/Ant-Media-Server/issues/6308

### CODE REVIEW

**Comment by mekya** [comment]
Hi @lastpeony ,

I've reviewed/deployed this branch to the ovh36 because HLSManifestModifier is also related to [this issue](https://github.com/ant-media/Ant-Media-Server/issues/6697)  Unfortunately, it's not working for me. 
- It appends the full content again. Check the zip file. 

[streamId_3RJyZU6ug (23).m3u8.zip](https://github.com/user-attachments/files/17784791/streamId_3RJyZU6ug.23.m3u8.zip)

- It returns as expected when HTTP is used. 
- I could not find specific test code for this fix. I think you could not write due to of HTTPS weird error. 
- Lastly, I've received this exception time to time because the original is empty. (`	String original = new String(originalData, StandardCharsets.UTF_8);`)  
```
2024-11-16 13:21:53,320 [https-jsse-nio2-0.0.0.0-5443-exec-6] ERROR i.a.f.HlsManifestModifierFilter - Error processing m3u8 filter:
io.lindstrom.m3u8.parser.PlaylistParserException: Invalid playlist. Expected #EXTM3U.
	at io.lindstrom.m3u8.parser.AbstractPlaylistParser.readPlaylist(AbstractPlaylistParser.java:79)
	at io.lindstrom.m3u8.parser.AbstractPlaylistParser.readPlaylist(AbstractPlaylistParser.java:62)
	at io.antmedia.filter.HlsManifestModifierFilter.doFilter(HlsManifestModifierFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at io.antmedia.filter.HttpForwardFilter.doFilter(HttpForwardFilter.java:74)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at io.antmedia.filter.TokenFilterManager.doFilter(TokenFilterManager.java:157)
```

**Comment by lastpeony** [comment]
Hello @mekya 
Strange. we also tested on ovh36 with @yashtandon113 

i will take a look at it again

**Comment by lastpeony** [comment]
Hello @mekya 
Just tested on ovh36 initial version of this branch and it works as expected on me.
image
https://ovh36.antmedia.io:5443/LiveApp/streams/teststream.m3u8?start=1731797705&end=1731797735


image

I think we need to check this together

**Comment by mekya** [comment]
Hi @lastpeony,

Thank you for your test. 

I've encountered weird behaviors. Let me tell the scenario

1.  It's working as expected if I use wget
2. It's not working if I download the same URL directly from Chrome
3. I copied the Curl command from Chrome Developer Tools and called it. Then it returns as expected.
4. I switched back to step 2 above and it starts work. 

Then everything works as expected. 

I am suspicious that some HTTP headers cause this problem. 

I'm checking currently. I'll update you if I find the root cause

**Pull request merged**
