### PR TITLE
Add rest method to import unregistered vod files

### PR DESCRIPTION
**Pull request by mustafaboleken**
https://github.com/ant-media/Ant-Media-Server/issues/4535

### CODE REVIEW

**Comment by mustafaboleken** [comment]
> I think the expectation is a little different.
> 
> User has several disks and would like to import files from these disks directly to Ant Media Server.
> 
> I think the expectation is something like that user just give the path of the `folder` to import and then Ant Media Server will import all these VoD files under the `folder` to panel directly.

I think, registering files under streams is also useful. I can add another parameter called the path to the Rest API and if the path is empty, the current solution could be the default behavior. How does it sound?

**Comment by asharamseervi** [comment]
> I think the expectation is a little different.
> 
> User has several disks and would like to import files from these disks directly to Ant Media Server.
> 
> I think the expectation is something like that user just give the path of the `folder` to import and then Ant Media Server will import all these VoD files under the `folder` to panel directly.

Hi, I was discussing this in community hour:
- Yes, one use case is this which is being targeted to develop. If I understood it correctly, this feature is enhancing multiple disks/directories of content on same server which wasn't mapped to vod/stream, right?
- Another, use case may be targeted, to import streams from other service provider which may be SaaS provider or any s3/s3-compitible bucket!

Let's progress with one and afterwords, second use-case may be targeted. Absolutely, @mustafaboleken including it to stream along vod will be much helpful. Thanks.

**Comment by mustafaboleken** [comment]
> > I think the expectation is a little different.
> > User has several disks and would like to import files from these disks directly to Ant Media Server.
> > I think the expectation is something like that user just give the path of the `folder` to import and then Ant Media Server will import all these VoD files under the `folder` to panel directly.
> 
> Hi, I was discussing this in community hour:
> 
> * Yes, one use case is this which is being targeted to develop. If I understood it correctly, this feature is enhancing multiple disks/directories of content on same server which wasn't mapped to vod/stream, right?
> * Another, use case may be targeted, to import streams from other service provider which may be SaaS provider or any s3/s3-compitible bucket!
> 
> Let's progress with one and afterwords, second use-case may be targeted. Absolutely, @mustafaboleken including it to stream along vod will be much helpful. Thanks.

You are right, let's consider getting data from other service providers as second phase. Can you please create an issue as feature request and we will add it to our roadmap.

**Comment by mustafaboleken** [comment]
This pr moves to https://github.com/ant-media/Ant-Media-Server/pull/4663

**Pull request closed without merging**
