### PR TITLE
Feature/seek feature

### LINKED ISSUE #3148: Seek on VoD streams

### PR DESCRIPTION
**Pull request by SelimEmre**
# Pull Request

This PR fixes #3148

### CODE REVIEW

**Comment by asharamseervi** [comment]
Hi @SelimEmre, any chance of merging it?

I thought I should remind you that you've worked on something awesome and forgot to merge ;)

**Comment by asharamseervi** [comment]
Hi @SelimEmre, any chance of merging it?

I thought I should remind you that you've worked on something awesome and forgot to merge ;)

**Comment by mekya** [comment]
This is for seeking the VoD files in WebRTC playback. 
Do you think the same way @asharamseervi ?

**Comment by mekya** [comment]
Closing this PR because this implementation has some kind of issues in backward seeking etc. 

New PR for this feature is here https://github.com/ant-media/Ant-Media-Server/pull/6150

**Pull request closed without merging**
